### ISSUE TITLE
rcc-03-chapter-checklist

### ISSUE THREAD

**Issue by IanMulvany** [sagepublishing/rich-context-book-2019#2]
- [x] Have draft chapter  
- [ ] Have title 
- [ ] Have Author List 
- [ ] Have affiliations
- [x] Have corresponding author
- [ ] Team has chapter template 
- [ ] Source of chapter 
- [x] Code is in github 
- [x] DOI assigned to code via zenodo 
- [ ] Model is in a model repo, e.g.
- [ ] Chapter is in standard format 
- [ ] Sent to peer review 
- [ ] Review comments received
- [ ] Revision in hand 
- [ ] Final submission in place

**Comment by IanMulvany** [comment]
code repo for this contribution https://github.com/allenai/coleridge-rich-context

**Comment by IanMulvany** [comment]
DOI for the code repo 10.5281/zenodo.2581628

**Comment by IanMulvany** [comment]
corresponding author Daniel King

**Comment by dakinggg** [comment]
@IanMulvany Sincere apologies, I made a mistake and managed to delete the original repo for our contribution. 
Here is a new repo with the same content: https://github.com/allenai/coleridge-rich-context-ai2
and its DOI: 10.5281/zenodo.3228495
