### ISSUE TITLE
rcc-17-chapter-checklist

### ISSUE THREAD

**Issue by IanMulvany** [sagepublishing/rich-context-book-2019#4]
- [ ] Have draft chapter  
- [ ] Have title 
- [ ] Have Author List 
- [ ] Have affiliations
- [ ] Have corresponding author
- [ ] Team has chapter template 
- [ ] Source of chapter 
- [ ] Code is in github 
- [ ] DOI assigned to code via zenodo 
- [ ] Model is in a model repo, e.g.
- [ ] Chapter is in standard format 
- [ ] Sent to peer review 
- [ ] Review comments received
- [ ] Revision in hand 
- [ ] Final submission in place
